# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('score', models.IntegerField()),
                ('state', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restfuldb.Games')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('pl', 'Player'), ('de', 'Developer')], max_length=2)),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='usergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restfuldb.Users'),
        ),
        migrations.AddField(
            model_name='games',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restfuldb.Users'),
        ),
    ]
