# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfuldb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
